extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - automake
        - autoconf
        - libtool
        - pkg-config
        - libluajit-5.1-dev
        - libpcap-dev
        - luajit
        - liblmdb-dev
        - libck-dev
        - libgnutls28-dev
        - liblz4-dev
        - libzstd-dev
    configure:
      command:
        - ./autogen.sh
        - ./configure
